In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv("vaccination-coverage-byVaccineType (3).csv")
df

pruid                    prename                  prfname    week_end  \
0         1                     Canada                   Canada  2020-12-19   
1         1                     Canada                   Canada  2020-12-19   
2         1                     Canada                   Canada  2020-12-19   
3        10  Newfoundland and Labrador  Terre-Neuve-et-Labrador  2020-12-19   
4        10  Newfoundland and Labrador  Terre-Neuve-et-Labrador  2020-12-19   
...     ...                        ...                      ...         ...   
4046     62                    Nunavut                  Nunavut  2021-10-23   
4047     62                    Nunavut                  Nunavut  2021-10-23   
4048     62                    Nunavut                  Nunavut  2021-10-23   
4049     62                    Nunavut                  Nunavut  2021-10-23   
4050     62                    Nunavut                  Nunavut  2021-10-23   

                   product_name  numtotal_atleast1dose numtotal_partially  \
0                  Not reported                    0.0                  0   
1     Pfizer-BioNTech Comirnaty                12360.0              12360   
2                       Unknown                    2.0                  2   
3                  Not reported                    0.0                  0   
4     Pfizer-BioNTech Comirnaty                  972.0                972   
...                         ...                    ...                ...   
4046           Moderna Spikevax                22319.0               2549   
4047               Not reported                    0.0                  0   
4048                      Other                    0.0                  0   
4049  Pfizer-BioNTech Comirnaty                 3560.0                693   
4050                    Unknown                    0.0                  0   

      numtotal_fully prop_atleast1dose prop_partially prop_fully  Unnamed: 11  \
0                0.0              0.00           0.00       0.00          NaN   
1                0.0              0.07           0.07       0.00          NaN   
2                0.0             <0.01          <0.01       0.00          NaN   
3                0.0              0.00           0.00       0.00          NaN   
4                0.0              0.19           0.19       0.00          NaN   
...              ...               ...            ...        ...          ...   
4046         19770.0             56.64           6.47      50.17          NaN   
4047             0.0                 0              0          0          NaN   
4048             0.0                 0              0          0          NaN   
4049          2867.0              9.03           1.76       7.28          NaN   
4050             0.0                 0              0          0          NaN   

      numweekdelta_atleast1dose  numweekdelta_fully  propweekdelta_partially  \
0                           NaN                 NaN                      NaN   
1                           NaN                 NaN                      NaN   
2                           NaN                 NaN                      NaN   
3                           NaN                 NaN                      NaN   
4                           NaN                 NaN                      NaN   
...                         ...                 ...                      ...   
4046                        NaN                 NaN                      NaN   
4047                        NaN                 NaN                      NaN   
4048                        NaN                 NaN                      NaN   
4049                        NaN                 NaN                      NaN   
4050                        NaN                 NaN                      NaN   

      propweekdelta_fully  
0                     NaN  
1                     NaN  
2                     NaN  
3                     NaN  
4                     NaN  
...                   ...  
40

In [ ]:
#1 understanding the data

In [8]:
df.head()

pruid                    prename                  prfname    week_end  \
0      1                     Canada                   Canada  2020-12-19   
1      1                     Canada                   Canada  2020-12-19   
2      1                     Canada                   Canada  2020-12-19   
3     10  Newfoundland and Labrador  Terre-Neuve-et-Labrador  2020-12-19   
4     10  Newfoundland and Labrador  Terre-Neuve-et-Labrador  2020-12-19   

                product_name  numtotal_atleast1dose numtotal_partially  \
0               Not reported                    0.0                  0   
1  Pfizer-BioNTech Comirnaty                12360.0              12360   
2                    Unknown                    2.0                  2   
3               Not reported                    0.0                  0   
4  Pfizer-BioNTech Comirnaty                  972.0                972   

   numtotal_fully prop_atleast1dose prop_partially prop_fully  Unnamed: 11  \
0             0.0              0.00           0.00       0.00          NaN   
1             0.0              0.07           0.07       0.00          NaN   
2             0.0             <0.01          <0.01       0.00          NaN   
3             0.0              0.00           0.00       0.00          NaN   
4             0.0              0.19           0.19       0.00          NaN   

   numweekdelta_atleast1dose  numweekdelta_fully  propweekdelta_partially  \
0                        NaN                 NaN                      NaN   
1                        NaN                 NaN                      NaN   
2                        NaN                 NaN                      NaN   
3                        NaN                 NaN                      NaN   
4                        NaN                 NaN                      NaN   

   propweekdelta_fully  
0                  NaN  
1                  NaN  
2                  NaN  
3                  NaN  
4                  NaN

In [9]:
df.tail()

pruid  prename  prfname    week_end               product_name  \
4046     62  Nunavut  Nunavut  2021-10-23           Moderna Spikevax   
4047     62  Nunavut  Nunavut  2021-10-23               Not reported   
4048     62  Nunavut  Nunavut  2021-10-23                      Other   
4049     62  Nunavut  Nunavut  2021-10-23  Pfizer-BioNTech Comirnaty   
4050     62  Nunavut  Nunavut  2021-10-23                    Unknown   

      numtotal_atleast1dose numtotal_partially  numtotal_fully  \
4046                22319.0               2549         19770.0   
4047                    0.0                  0             0.0   
4048                    0.0                  0             0.0   
4049                 3560.0                693          2867.0   
4050                    0.0                  0             0.0   

     prop_atleast1dose prop_partially prop_fully  Unnamed: 11  \
4046             56.64           6.47      50.17          NaN   
4047                 0              0          0          NaN   
4048                 0              0          0          NaN   
4049              9.03           1.76       7.28          NaN   
4050                 0              0          0          NaN   

      numweekdelta_atleast1dose  numweekdelta_fully  propweekdelta_partially  \
4046                        NaN                 NaN                      NaN   
4047                        NaN                 NaN                      NaN   
4048                        NaN                 NaN                      NaN   
4049                        NaN                 NaN                      NaN   
4050                        NaN                 NaN                      NaN   

      propweekdelta_fully  
4046                  NaN  
4047                  NaN  
4048                  NaN  
4049                  NaN  
4050                  NaN

In [10]:
df.shape

(4051, 16)

In [11]:
df.describe

<bound method NDFrame.describe of       pruid                    prename                  prfname    week_end  \
0         1                     Canada                   Canada  2020-12-19   
1         1                     Canada                   Canada  2020-12-19   
2         1                     Canada                   Canada  2020-12-19   
3        10  Newfoundland and Labrador  Terre-Neuve-et-Labrador  2020-12-19   
4        10  Newfoundland and Labrador  Terre-Neuve-et-Labrador  2020-12-19   
...     ...                        ...                      ...         ...   
4046     62                    Nunavut                  Nunavut  2021-10-23   
4047     62                    Nunavut                  Nunavut  2021-10-23   
4048     62                    Nunavut                  Nunavut  2021-10-23   
4049     62                    Nunavut                  Nunavut  2021-10-23   
4050     62                    Nunavut                  Nunavut  2021-10-23   

                 

In [12]:
df.columns

Index(['pruid', 'prename', 'prfname', 'week_end', 'product_name',
       'numtotal_atleast1dose', 'numtotal_partially', 'numtotal_fully',
       'prop_atleast1dose', 'prop_partially', 'prop_fully', 'Unnamed: 11',
       'numweekdelta_atleast1dose', 'numweekdelta_fully',
       'propweekdelta_partially', 'propweekdelta_fully'],
      dtype='object')

In [13]:
df.nunique()

pruid                          14
prename                        14
prfname                        14
week_end                       45
product_name                    9
numtotal_atleast1dose        2162
numtotal_partially           1786
numtotal_fully               1718
prop_atleast1dose            1199
prop_partially                799
prop_fully                    939
Unnamed: 11                     0
numweekdelta_atleast1dose       0
numweekdelta_fully              0
propweekdelta_partially         0
propweekdelta_fully             0
dtype: int64

In [15]:
df['propweekdelta_partially'].unique()

array([nan])

In [16]:
df['propweekdelta_fully'].unique()

array([nan])

In [17]:
df['pruid'].unique()

array([ 1, 10, 12, 24, 46, 47, 59, 60, 61, 62, 11, 13, 48, 35])

In [18]:
#2 Cleaning the database

In [19]:
df.isnull().sum

<bound method DataFrame.sum of       pruid  prename  prfname  week_end  product_name  numtotal_atleast1dose  \
0     False    False    False     False         False                  False   
1     False    False    False     False         False                  False   
2     False    False    False     False         False                  False   
3     False    False    False     False         False                  False   
4     False    False    False     False         False                  False   
...     ...      ...      ...       ...           ...                    ...   
4046  False    False    False     False         False                  False   
4047  False    False    False     False         False                  False   
4048  False    False    False     False         False                  False   
4049  False    False    False     False         False                  False   
4050  False    False    False     False         False                  False   

      nu